// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	BulkInsertTranslations(ctx context.Context, arg *BulkInsertTranslationsParams) ([]*Translation, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteUser(ctx context.Context, id int64) error
	GetAllTranslationsByHashes(ctx context.Context, arg *GetAllTranslationsByHashesParams) ([]*Translation, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserById(ctx context.Context, id int64) (*User, error)
	ListAllUsers(ctx context.Context) ([]*User, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
