// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translations_query.sql

package repository

import (
	"context"
)

const getTranslationByHash = `-- name: GetTranslationByHash :one
SELECT id, normalized_hash, language_code, original_text, translated_text, confidence_score, provider, created_at FROM translations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTranslationByHash(ctx context.Context, id int32) (*Translation, error) {
	row := q.db.QueryRow(ctx, getTranslationByHash, id)
	var i Translation
	err := row.Scan(
		&i.ID,
		&i.NormalizedHash,
		&i.LanguageCode,
		&i.OriginalText,
		&i.TranslatedText,
		&i.ConfidenceScore,
		&i.Provider,
		&i.CreatedAt,
	)
	return &i, err
}
